Upload unprocessed and processed videos to Cloud Storage
MISW4204-2024-desarrollo-sw-nube/interna-FPV-drone-racing-league pull request #23
Opened 2024-04-30 01:45 UTC by santi8194

En este PR está la funcionalidad para integrar con Google Cloud Storage y subir los videos no-procesados y procesados.

Falta probar en el ambiente de producción con las instancias VM.

2024-04-30 03:55 UTC, ccpinzonh1 requested changes
Algo me dice que necesitamos revisar bien la subida de los archivos al bucket

2024-04-30 03:55 UTC, ccpinzonh1 commented on uploader/api_commands.py
> +    )
Question: 
necesitamos este print

2024-04-30 03:55 UTC, ccpinzonh1 commented on uploader/async_video_processor.py
> +        )
Question:
Este print es necesario

2024-04-30 03:55 UTC, ccpinzonh1 commented on uploader/api_commands.py
>      file.close()
Creo que esto ya no es necesario. podemos eliminarlo?

2024-04-30 03:55 UTC, ccpinzonh1 commented on uploader/api_commands.py
> +    bucket_name = 'ifpv-videos'
Podemos estandarizar el nombre del bucket en una variable de entorno ?

2024-04-30 03:55 UTC, ccpinzonh1 commented on uploader/async_video_processor.py
> +        bucket_name = 'ifpv-videos'
POdemos estandarizar el nombre del bucket en una variable de entorno ?

2024-04-30 03:55 UTC, ccpinzonh1 commented on uploader/async_video_processor.py
en la siguiente linea de codigo. 
https://github.com/MISW4204-2024-desarrollo-sw-nube/interna-FPV-drone-racing-league/blob/5c47a857850fd158bb619ac00a7c21cba08a11af/uploader/async_video_processor.py#L30-L32
No deberiamos leer el archivo del google cloud bucket?

2024-04-30 03:55 UTC, ccpinzonh1 commented on uploader/async_video_processor.py
Deberiamos subir la imagen al bucket o la dejamos en la maquina ?
https://github.com/MISW4204-2024-desarrollo-sw-nube/interna-FPV-drone-racing-league/blob/5c47a857850fd158bb619ac00a7c21cba08a11af/uploader/async_video_processor.py#L41
google nos cobra por lectura o por carga ?

2024-04-30 03:55 UTC, ccpinzonh1 commented on uploader/async_video_processor.py
>          processed_video.write_videofile(processed_file_name)
Creo que esto ya no es necesario

2024-04-30 03:55 UTC, ccpinzonh1 commented on uploader/async_video_processor.py
> +        destination_blob_name = f"processed_videos/processed_{unprocessed_file_name}"
Para que necesitamos el source file name ? no podemos trabajar con el archivo directamente ?

2024-04-30 03:55 UTC, ccpinzonh1 commented on uploader/async_video_processor.py
> +        generation_match_precondition = 0
```
When you pass the if_generation_match parameter to a method that retrieves a blob resource (e.g., Blob.reload) or modifies the blob (e.g., Blob.update), the operation becomes conditional. 
The operation will only be performed if the blob’s current generation matches the value provided in the if_generation_match field.
In other words, if_generation_match is used to ensure that the object is in the expected state, allowing you to perform safe read-modify-write updates and conditional operations on objects. 
This can be particularly useful in scenarios where you want to avoid conflicts due to concurrent modifications.
```
Segun entiendo `if_generation_match` no aplica para nuestro caso.

2024-04-30 03:55 UTC, ccpinzonh1 commented on uploader/api_commands.py
Estas lineas de codigo ya no serian necesarias.
https://github.com/MISW4204-2024-desarrollo-sw-nube/interna-FPV-drone-racing-league/blob/5c47a857850fd158bb619ac00a7c21cba08a11af/uploader/api_commands.py#L48-L49

2024-04-30 03:55 UTC, ccpinzonh1 commented on uploader/api_commands.py
> +    storage_client = storage.Client()
Como sabemos que se esta conectando al proyecto de GCP? 
Necesitamos habilitar algunas credenciales o alog ?

2024-04-30 03:55 UTC, ccpinzonh1 commented on uploader/api_commands.py
> +    generation_match_precondition = 0
```
When you pass the if_generation_match parameter to a method that retrieves a blob resource (e.g., Blob.reload) or modifies the blob (e.g., Blob.update), the operation becomes conditional. 
The operation will only be performed if the blob’s current generation matches the value provided in the if_generation_match field.
In other words, if_generation_match is used to ensure that the object is in the expected state, allowing you to perform safe read-modify-write updates and conditional operations on objects. 
This can be particularly useful in scenarios where you want to avoid conflicts due to concurrent modifications.
```
Segun entiendo `if_generation_match` no aplica para nuestro caso.

2024-04-30 03:55 UTC, ccpinzonh1 commented on uploader/api_commands.py
> +    blob.upload_from_filename(source_file_name, if_generation_match=generation_match_precondition)
podemos probar con esto ??? no se si sea posible, para evitar tener que guardar el archivo y volverlo a cargar.
```suggestion
    blob.upload_from_file(file)
```

2024-04-30 03:55 UTC, ccpinzonh1 commented on uploader/api_commands.py
Creo que estas lineas de codigo ya no deberian ser responsabilidad del apicommands. 
https://github.com/MISW4204-2024-desarrollo-sw-nube/interna-FPV-drone-racing-league/blob/5c47a857850fd158bb619ac00a7c21cba08a11af/uploader/api_commands.py#L34-L35
 y lo unico que deberiamos mandarle al celery task 
 https://github.com/MISW4204-2024-desarrollo-sw-nube/interna-FPV-drone-racing-league/blob/5c47a857850fd158bb619ac00a7c21cba08a11af/uploader/api_commands.py#L93-L97
 deberia ser el  `destination_blob_name` y el `video.id`. Sin embargo, se que desde el celery no tenemos acceso al app, entonces probablemente el logo tambien. pero no estoy seguro.

2024-04-30 03:55 UTC, ccpinzonh1 commented on uploader/api_commands.py
> +    destination_blob_name = f"unprocessed_videos/{filename_with_timestamp}"
Creo que el `destination_blob_name` que deberiamos manejar  es 
```python
destination_blob_name = os.path.join(current_unprocessed_folder, filename_with_timestamp)
```

2024-04-30 03:55 UTC, ccpinzonh1 commented on uploader/api_commands.py
Podemos envolver todo el proceso en un try/catch , en caso de que existan problemas al momento de subir el archivo al bucket, le podamos informar al usuario que no se pudo cargar el archivo

2024-04-30 03:55 UTC, ccpinzonh1 commented on uploader/async_video_processor.py
> +        destination_blob_name = f"processed_videos/processed_{unprocessed_file_name}"
```suggestion
        destination_blob_name = processed_file_name
```

2024-04-30 13:21 UTC, santi8194 commented on uploader/api_commands.py
> +    )
No, se puede quitar.

2024-04-30 13:21 UTC, santi8194 commented on uploader/async_video_processor.py
> +        )
No, se puede quitar

2024-04-30 13:25 UTC, santi8194 commented on uploader/api_commands.py
>      file.close()
En la entrega no dice explicitamente que eliminemos la funcionalidad de NFS. Pero tampoco estoy muy seguro.
<img width="820" alt="image" src="https://github.com/MISW4204-2024-desarrollo-sw-nube/interna-FPV-drone-racing-league/assets/4406788/19bf8098-7a26-427b-ae57-2ecc3f6285b3">

2024-04-30 13:26 UTC, santi8194 commented on uploader/api_commands.py
> +    bucket_name = 'ifpv-videos'
De one!

2024-04-30 13:27 UTC, santi8194 commented on uploader/api_commands.py
> +    blob.upload_from_filename(source_file_name, if_generation_match=generation_match_precondition)
No estoy seguro se debamos quitar la funcionalidad de NFS.

2024-04-30 13:33 UTC, santi8194 commented on uploader/api_commands.py
> +    destination_blob_name = f"unprocessed_videos/{filename_with_timestamp}"
`current_unprocessed_folder ` es la ruta completa del folder. Lo que queremos en `destination_blob_name ` es solo el nombre de la carpeta y el filename. No quise usar la variable de entorno que tenemos para el nombre de la carpeta porque son dos destinos diferentes. si se cambia, tenemos que estar seguros de que exista en el bucket. 

También podría crearle una nueva variable de entorno para el nombre de la carpeta en GCP.

2024-04-30 13:34 UTC, santi8194 commented on uploader/api_commands.py
De acuerdo.

2024-05-01 03:35 UTC, santi8194 commented on uploader/api_commands.py
>      file.close()
Crearemos otro PR para esto

2024-05-01 03:39 UTC, santi8194 commented on uploader/api_commands.py
> +    blob.upload_from_filename(source_file_name, if_generation_match=generation_match_precondition)
Crearemos otro PR para esto. Cuando quitemos el NFS, se puede subir el video a Cloud Storage desde memoria.

2024-05-01 03:45 UTC, santi8194 commented on uploader/api_commands.py
Crearemos otro PR para esto

2024-05-01 03:45 UTC, santi8194 commented on uploader/api_commands.py
Crearemos otro PR para esto

2024-05-01 03:49 UTC, santi8194 commented on uploader/api_commands.py
> +    storage_client = storage.Client()
La app se conectará a GCP usando algo que llaman Application Default Credentials (ADC).
Aqui explican cómo configurarlo: https://cloud.google.com/docs/authentication/provide-credentials-adc

Para configurarlo local: https://cloud.google.com/docs/authentication/provide-credentials-adc#local-dev
Para configruarlo en las instancias VM: https://cloud.google.com/docs/authentication/provide-credentials-adc#attached-sa

2024-05-01 03:55 UTC, santi8194 commented on uploader/api_commands.py
> +    generation_match_precondition = 0
Es cierto, por ahí leí que para archivos nuevos lo recomendado es dejarlo en 0. Ese debe ser el por defecto, entonces lo quitaré.

2024-05-01 04:00 UTC, santi8194 commented on uploader/async_video_processor.py
Cloud Storage parece ser economico. Estos son los precios: https://cloud.google.com/storage#pricing

2024-05-01 04:00 UTC, santi8194 commented on uploader/async_video_processor.py
Si, en el siguiente PR

2024-05-01 04:02 UTC, santi8194 commented on uploader/async_video_processor.py
> +        bucket_name = 'ifpv-videos'
Done.

2024-05-01 04:08 UTC, santi8194 commented on uploader/async_video_processor.py
> +        destination_blob_name = f"processed_videos/processed_{unprocessed_file_name}"
En el siguiente PR usamos el file en memoria en vez del file system.

2024-05-01 20:33 UTC, AfLosada approved these changes

2024-05-02 20:10 UTC, ccpinzonh1 approved these changes

2024-05-03 01:26 UTC, merged